### ISSUE TITLE
Unable to run a highstate with the salt-iocage-formula

### ISSUE THREAD

**Issue by crispinon** [bougie/salt-iocage-formula#3]
Dear Bougie,

With just one template and no jails defined var 'jails' will be:
['', 'STATE=down,JID=-,TAG=FreeBSD_10.2-RELEASE_TEMPLATE,BOOT=off,UUID=xxxxxxx-46a8-11e5-8019-6805ca2d9ff3'] and causes "def managed(name, properties=None, jail_type="full", template_id=None, **kwargs):" to except.

**Comment by sidred** [comment]
Just submitted a pull request. please check if it solves the issue

**Comment by crispinon** [comment]
Dear Sid, Bougie,

Thanks for the update. I will test.
I have tried to solve this and tried:

 77:       for jail in filter(bool, jails):

This seems to work as well.

New to Git _and_ Python. Will try to clone and make a pull request in case of updates/other issues.
Looking to incorporate jail_type and template_id in pillar.

Kind regards,

Crispinon

**Comment by crispinon** [comment]
## Summary

Succeeded: 5

## Failed:    0

Total states run:     5

Issue is solved.

**Comment by bougie** [comment]
Thanks to sidred10 for solving this issue !
